# Generated by Django 5.0.4 on 2024-04-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('parent_item__name', 'parent_item__parent_item__name'), 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='parent_point',
            new_name='parent_item',
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('name', 'parent_item')},
        ),
    ]
